backend/authentication/models.py
Added roles to db in order to allow users' access to some views
=> FEAT: USER ROLES ADDED TO DB

backend/authentication/models.py, backend/backend/schema.py, backend/requirements.txt, backend/social/mutations.py
SE LA IMPLEMENTADO LOS ENDPOINTS DE EDICIÓN DE USUARIO, ADICIÓN Y ELIMINACIÓN DE UN ROL A UN USUARIO Y ELIMINACIÓN DE UNA ETIQUETA A UN USUARIO.
=> FEAT: ENDPOINTS DE PERFIL  DE USUARIO

client/package.json, client/src/components/flatterModal.js, client/src/components/header/loginRegisterForm.js, client/src/components/superAnimatedButton/shapes.js, client/src/components/superAnimatedButton/superAnimatedButton.js, client/src/components/superAnimatedButton/superAnimatedButtonSettings.js, client/src/components/superAnimatedButton/useSmoothTransform.js, client/src/sections/header.js, client/src/sections/solidButton.js, client/src/static/css/components/flatterModal.css, client/src/static/css/components/loginRegisterForm.css, client/src/static/css/components/superAnimatedButton.css, client/src/static/css/globals.css, client/src/static/css/sections/button.css, client/yarn.lock
Se han diseñado estos formularios. Se puede acceder a ellos mediante los botones "registrarse" y "acceder" del header.
También se ha refactorizado el componente "SolidButton".
=> FEAT: DISEÑO FORMULARIOS LOGIN Y REGISTRO

backend/backend/schema.py, backend/mainApp/models.py, backend/mainApp/mutations.py, backend/mainApp/queries.py, backend/mainApp/types.py
I have added two queries that allow obtaining all the available tags and the tags of a property. I have also added a mutation that allows to associate a property with a tag
=> FEAT: Property tagging

backend/mainApp/fixture/properties.json
=> Task/128 properties.json done

backend/mainApp/queries.py
A query that allows you to get all the properties of an owner
=> FEAT: Find properties by owner

backend/authentication/fixtures/testers.json, backend/mainApp/fixtures/properties.json
=> FEAT: DATOS USUARIOS PILOTOS

client/src/sections/footer.js
He arreglado el bug del footer, el fallo se debía a que el archivo JavaScript no tenía las clases en los elementos. De paso he añadido el enlace **Aviso de privacidad** al footer.
=> FIX: ARREGLA CLASES FOOTER

client/src/api/propertiesAPI.js, client/src/pages/propertyDetails.js
En la vista de detalles de vivienda, puedes editar la propiedad si eres su propietario. Cabe recordar que sigue existiendo el bug de que se clone la propiedad pero sin fotos.
=> FEAT: EDITAR PROPIEDAD EN DETALLES

client/package.json, client/src/App.js, client/src/api/tagsAPI.js, client/src/components/inputs/tagSelector.js, client/yarn.lock
Crea componente TagSelector que es un select multiple que carga las tags de la API.
Se añade la dependencia 'react-select' al proyecto.
El name del select es tags, mientras que los valores son las ids de las etiquetas aunque se muestren los nombres a la hora de visualizarlos.
Se puede ver el compononente en la url /prueba. Este path puede ser eliminado una vez se pruebe la funcionalidad.
=> FEAT: COMPONENTE TagSelector

backend/authentication/types.py, backend/mainApp/models.py, backend/social/mutations.py, client/src/forms/commentsForm.js, client/src/libs/validators/commentsValidators.js
La relación en las valoraciones ha sido arreglada.
Cierra #221
=> FIX: RELACION VALORACIONES

backend/mainApp/mutations.py, client/src/static/css/components/carousel.css, client/src/static/css/components/slideShow.css, client/src/static/css/components/userCard.css, client/src/static/css/sections/chat.css
Se añade el atributo "object-fit: cover" a las imagenes del carrusel de destacados,
a las imagenes de perfil de userCard y las imagenes de la vista de detalle de propiedades slideShow.
=> FIX: IMAGENES DISTORSIONADAS

backend/authentication/mutations.py, backend/social/mutations.py
SE HA IMPLEMENTADO UNA MUTACIÓN PARA ESTABLECER LAS ETIQUETAS DESCRIPTIVAS DEL SISTEMA QUE EL USUARIO QUIERA ESTABLECERSE.
=> FEAT: ENDPOINT DE ETIQUETAS DE USUARIO

backend/authentication/mutations.py, backend/mainApp/admin.py, backend/mainApp/models.py, backend/mainApp/queries.py, backend/mainApp/types.py
I addes queries that allows you to search petitions by owner, by requester and filter the petitions by dates
=> FEAT: Queries to petitions operations

client/src/App.js, client/src/pages/accountSettings.js, client/src/pages/favouritesProperties.js, client/src/static/css/sections/button.css
He creado la nueva ruta para los favoritos, la vista y un botón en el perfil privado.
=> FEAT: DISEÑO PISOS FAVORITOS

backend/authentication/models.py, backend/mainApp/fixtures/properties.json, backend/mainApp/models.py
task waiting for revision
IMPORTANT-> Changed favourite_propertiest in Flatter_user(authentication) to interested_users in Property (mainApp) with properties.json
=> Task\192 done with changes: favourite_properties -> interested_users

backend/authentication/models.py, backend/authentication/mutations.py
=> Task 189 done

backend/authentication/types.py, backend/social/mutations.py
SE HAN IMPLMENTADO QUE LA MUTACIÓN DEVUELVA UN ATRIBUTO DERIVADO QUE CALCULE LA EDAD DEL USUARIO. ADEMÁS, SE HAN AÑADIDO ALGUNAS MODIFICACIONES EN LA EDICIÓN DE LA FECHA DE NACIMIENTO.
=> FEAT: CAMBIOS CON EL ATRIBUTO FEHCA DE NACIMIENTO.

backend/mainApp/mutations.py, backend/mainApp/queries.py
One new query that allows you to get the petition of  a RENTER  to a property and one mutation that allows you to delete a petition
=> FEAT: Backend methods requested

backend/mainApp/models.py, backend/mainApp/mutations.py, client/src/static/css/pages/ownerProperties.css
Toda la info al respecto en el ultimo commit
=> FIX: CORREGIDO ERROR DE DESCRIPCIÓN.

client/src/api/usersAPI.js, client/src/components/flatterModal.js, client/src/components/inputs/tagSelector.js, client/src/components/profile/publicProfileCard.js, client/src/static/css/components/publicProfileCard.css, client/src/static/css/sections/tagSelector.css
Ahora los usuarios pueden actualizar sus etiquetas en su perfil público. El componente tagSelector se ha modificado declarando tres props:
- defaultValues: array de etiquetas que se mostrarán por defecto.
- options: array de etiquetas que se mostrarán en el selector.
- max: número máximo de etiquetas que se pueden seleccionar. 
También se crea la query updatePublicProfile para actualizar el perfil público y sus etiquetas.
=> FEAT: FUNCIONALIDAD TAGS PERFIL PÚBLICO

backend/mainApp/models.py, backend/mainApp/tests.py
Se han añadido nuevos tests de inmueble, para mutations, queries y modelo, con casos positivos y negativos dentro del módulo de mainApp.
=> TEST: TESTS DE INMUEBLE

client/src/forms/propertiesForm.js
Cambia el nombre del tag de 'título de la propiedad' por 'nombre del inmueble'.
=> FIX: CAMBIAR TAG DE INPUT NOMBRE INMBUEBLE

client/src/api/usersAPI.js, client/src/components/profile/commentsBox.js, client/src/forms/commentsForm.js
Ahora las opciones disponibles de relacion, cuando se crea un comentario a un usuario, se cargan desde la base de datos.
=> FEAT: OPCIONES RELACIONES ENTRE USUARIOS

backend/mainApp/mutations.py
Mutacion añadida que permite asociar un inquilino a un piso una vez ha realizado el proceso de aceptación y pago
=> FEAT: Mutation added

backend/social/queries.py, backend/social/recommendations.py, client/src/App.js, client/src/api/usersAPI.js, client/src/pages/recommendedUsers.js, client/src/sections/header.js
Crea una vista donde aparece un listado con los usuarios recomendados para el usuario logueado.
=> FEAT: VISTA USUARIOS RECOMENDADOS

client/src/forms/propertyRequestsInputs.js, client/src/pages/propertyDetails.js
Ahora cada usuario tendrá un mensaje personalizado en función de su nombre, edad y profesión. Se ha editado el archivo de propertyDetails debido a que necesitaba traerme la información de allí para el modal.
=> FEAT: FUNCIONALIDAD DE MENSAJE PERSONALIZADO TERMINADA.

backend/authentication/queries.py, backend/authentication/types.py, backend/mainApp/queries.py, backend/mainApp/tests.py, backend/mainApp/types.py
I added to the required queries pagination logic
=> FEAT: Pagination added

backend/authentication/models.py, backend/mainApp/fixtures/demo.json
añadido además un nuevo atributo compensación al cambiar de plan
=> añadidos contratos a demo.json

backend/social/tests_mutations.py, backend/social/tests_queries.py
SE HAN IMPLEMENTADO LAS PRUEBAS DE MODELO, QUERIES Y MUTATIONS CORRESPONDIENTES AL SPRINT 2.
TAMBIÉN SE HAN REVISADO Y CORREGIDO LAS PRUEBAS DE MODELOS CORREGIDOS O AFECTADOS POR CAMBIOS EN EL BACKEND.
=> TEST: IMPLEMENTACIÓN DE PRUEBAS UNITARIAS DEL SPRINT 2

backend/social/mutations.py
=> FEAT: MEJORA VALIDACION TOKEN

backend/mainApp/queries.py, backend/mainApp/tests.py
Se agregaron los tests correspondientes a queries y mutations del grupo 2.
=> TEST: NUEVOS TESTS DE INMUEBLE Y PETICIONES

backend/social/tests_mutations.py, backend/social/tests_queries.py
SE HAN CORREGIDO AQUELLOS TESTS QUE SE HABÍAN VISTO AFECTADOS POR LA INCORPORACIÓN DEL TOKEN DE USUARIO.
=> TEST: CORRECCIÓN DE TESTS DE TOKEN

backend/requirements.txt, backend/social/tests_selenium.py
Se han implementado los tests End to End con Selenium del módulo social. 
Se han llevado a cabo pruebas para examinar:
- Login de usuario.
- Registro de usuario.
- Edición de perfil privado.
- Edición de perfil público.
- Creación de chats (logueo, adquisión de plan avanzado, búsqueda de otros usuarios, creación de un chat e interacción)
=> TEST: IMPLEMENTACIÓN DE TESTS END TO END

backend/authentication/models.py, backend/mainApp/fixtures/demo.json, backend/social/mutations.py, client/src/api/usersAPI.js, client/src/components/profile/publicProfileCard.js, client/src/pages/accountSettings.js, client/src/pages/pricingPage.js, client/src/pages/publicProfile.js, client/src/pages/unloggedPricingPage.js, client/yarn.lock
=> VALIDACIONES PLANES
